/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S300095291
 */
public class FRMmain extends javax.swing.JFrame {

    /**
     * Creates new form FRMmain
     */
    public FRMmain() {
        initComponents();
            getContentPane().setBackground(new java.awt.Color(170, 206, 226)); //sets background colour
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        TxtReplace = new javax.swing.JTextField();
        BTNReplace = new javax.swing.JButton();
        TxtLetter = new javax.swing.JTextField();
        LblCaps = new javax.swing.JLabel();
        Lbl4th = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblLen = new javax.swing.JLabel();
        Txt4th = new javax.swing.JTextField();
        LblString = new javax.swing.JLabel();
        BTN4th = new javax.swing.JButton();
        LblLetter = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LblChar = new javax.swing.JLabel();
        Txtone = new javax.swing.JTextField();
        BTNString = new javax.swing.JButton();
        LblReplace = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtString = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtLen = new javax.swing.JTextField();
        BTNLen = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtCaps = new javax.swing.JTextField();
        TxtChar = new javax.swing.JTextField();
        BTNChar = new javax.swing.JButton();
        BTNCaps = new javax.swing.JButton();
        Txttwo = new javax.swing.JTextField();
        BTNLetter = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Enter a string that contains at least one \"a\". The program will replace all occurences of the letter \"a\" with \"x\". ");

        TxtReplace.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtReplaceActionPerformed(evt);
            }
        });

        BTNReplace.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNReplace.setText("Replaces \"a\"");
        BTNReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReplaceActionPerformed(evt);
            }
        });

        TxtLetter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLetterActionPerformed(evt);
            }
        });

        LblCaps.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblCaps.setText("ANSWER");

        Lbl4th.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        Lbl4th.setText("ANSWER");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Enter a string. The program will output the character at the fourth spot. ");

        LblLen.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblLen.setText("ANSWER");

        Txt4th.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt4th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt4thActionPerformed(evt);
            }
        });

        LblString.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblString.setText("ANSWER");

        BTN4th.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTN4th.setText("4th Spot");
        BTN4th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN4thActionPerformed(evt);
            }
        });

        LblLetter.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblLetter.setText("ANSWER");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Enter two strings. The program will output whether or not they are identical. ");

        LblChar.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblChar.setText("ANSWER");

        Txtone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txtone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtoneActionPerformed(evt);
            }
        });

        BTNString.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNString.setText("Identical?");
        BTNString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNStringActionPerformed(evt);
            }
        });

        LblReplace.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblReplace.setText("ANSWER");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Enter a string and a letter. The program will output whether or not the letter is found in the string.");

        TxtString.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStringActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Enter a string that is at least 8 chararter long. The program will output characters 4 to 6. ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setText("Krish's Super String Software");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Enter an string. The program will output the number of characters in the String.");

        TxtLen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtLen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLenActionPerformed(evt);
            }
        });

        BTNLen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNLen.setText("Length");
        BTNLen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Enter a string using lowercase letters. The program will output the string in all captial letters.");

        TxtCaps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCapsActionPerformed(evt);
            }
        });

        TxtChar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCharActionPerformed(evt);
            }
        });

        BTNChar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNChar.setText("Characters 4 to 6");
        BTNChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCharActionPerformed(evt);
            }
        });

        BTNCaps.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNCaps.setText("ALL CAPS");
        BTNCaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCapsActionPerformed(evt);
            }
        });

        Txttwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txttwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxttwoActionPerformed(evt);
            }
        });

        BTNLetter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNLetter.setText("Letter Found?");
        BTNLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLetterActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NGjZA49qsfv6JGpCceV2yJ-320-80.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\S300095291\\Downloads\\104104901-rainbow-colored-yarn-balls-viewed-from-above_256x256_crop_center_d2e661bf-a9ab-49d9-997e-b.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTNReplace)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblReplace))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtLen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNLen)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblLen))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Txt4th, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTN4th)
                                                .addGap(18, 18, 18)
                                                .addComponent(Lbl4th))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNCaps)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblCaps))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Txtone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Txttwo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNString)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblString))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtString, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxtLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNLetter)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblLetter))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtChar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNChar)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblChar)))
                                        .addGap(201, 201, 201)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)))))
                            .addComponent(jLabel5)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNLen)
                                    .addComponent(LblLen))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtCaps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNCaps)
                                    .addComponent(LblCaps)))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt4th, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN4th)
                            .addComponent(Lbl4th))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txtone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNString)
                            .addComponent(LblString)
                            .addComponent(Txttwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNLetter)
                            .addComponent(LblLetter))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtChar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNChar)
                    .addComponent(LblChar))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNReplace)
                    .addComponent(LblReplace))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtReplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtReplaceActionPerformed

    private void BTNReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReplaceActionPerformed
        // TODO add your handling code here:

        String replaces = TxtReplace.getText(); //gets the input text from the text boxes and stores in a variable 
        LblReplace.setText(replaces.replace("a", "x")); //replaces all letter a's in text with x and sets text box to it

    }//GEN-LAST:event_BTNReplaceActionPerformed

    private void TxtLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLetterActionPerformed

    private void Txt4thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt4thActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt4thActionPerformed

    private void BTN4thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN4thActionPerformed
        // TODO add your handling code here:

        String fourth = Txt4th.getText(); //gets the input text from the text boxes and stores in a variable 
        Lbl4th.setText(String.valueOf(fourth.charAt(3))); //sets text box to 4th character of your string 

    }//GEN-LAST:event_BTN4thActionPerformed

    private void TxtoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtoneActionPerformed

    private void BTNStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNStringActionPerformed
        // TODO add your handling code here:

        String one = Txtone.getText(); //gets the input text from the text boxes and stores in a variable 
        String two = Txttwo.getText(); //gets the input text from the text boxes and stores in a variable 
        
        if (one.equals(two)){ //if statement to chec whether both strings are the same or not
            LblString.setText("Identical"); //sets text box to identical
        }
        else{
            LblString.setText("Not Identical"); //sets text box to not idetical
        }

    }//GEN-LAST:event_BTNStringActionPerformed

    private void TxtStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStringActionPerformed

    private void TxtLenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLenActionPerformed

    private void BTNLenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLenActionPerformed
        // TODO add your handling code here:

        int len = TxtLen.getText().length(); //gets the length of the text of the input box 
        LblLen.setText(String.valueOf(len)); //sets answer to the string value of the length of the string 

    }//GEN-LAST:event_BTNLenActionPerformed

    private void TxtCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCapsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCapsActionPerformed

    private void TxtCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCharActionPerformed

    private void BTNCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCharActionPerformed
        // TODO add your handling code here:

        String charac = TxtChar.getText(); //gets the input text from the text boxes and stores in a variable
        LblChar.setText(String.valueOf(charac.subSequence(3, 6)));  //prints the set of characters in the string from 4-6

    }//GEN-LAST:event_BTNCharActionPerformed

    private void BTNCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCapsActionPerformed
        // TODO add your handling code here:
        
        String cappy = TxtCaps.getText(); //gets the input text from the text boxes and stores in a variable
        LblCaps.setText(String.valueOf(cappy.toUpperCase())); //sets whole string to capitals and outputs it on the text box        
    }//GEN-LAST:event_BTNCapsActionPerformed

    private void TxttwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxttwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxttwoActionPerformed

    private void BTNLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLetterActionPerformed
        // TODO add your handling code here:
        
        String lett = TxtLetter.getText(); //gets the input text from the text boxes and stores in a variable
        String stringy = TxtString.getText(); //gets the input text from the text boxes and stores in a variable
        LblLetter.setText(stringy.contains(lett) ? "Yes" : "No"); //turnary statement that prints yes if the string contains the other string in it and no if not


    }//GEN-LAST:event_BTNLetterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN4th;
    private javax.swing.JButton BTNCaps;
    private javax.swing.JButton BTNChar;
    private javax.swing.JButton BTNLen;
    private javax.swing.JButton BTNLetter;
    private javax.swing.JButton BTNReplace;
    private javax.swing.JButton BTNString;
    private javax.swing.JLabel Lbl4th;
    private javax.swing.JLabel LblCaps;
    private javax.swing.JLabel LblChar;
    private javax.swing.JLabel LblLen;
    private javax.swing.JLabel LblLetter;
    private javax.swing.JLabel LblReplace;
    private javax.swing.JLabel LblString;
    private javax.swing.JTextField Txt4th;
    private javax.swing.JTextField TxtCaps;
    private javax.swing.JTextField TxtChar;
    private javax.swing.JTextField TxtLen;
    private javax.swing.JTextField TxtLetter;
    private javax.swing.JTextField TxtReplace;
    private javax.swing.JTextField TxtString;
    private javax.swing.JTextField Txtone;
    private javax.swing.JTextField Txttwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
