
import java.io.*;
import java.text.DecimalFormat;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S300095291
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    double pricet = 0;// Initialize the total price.
    double grand;      // Variable for the final total price.

    int MangC = 0;     // Counter for Mangoes.
    int DragC = 0;     // Counter for Dragonfruits.
    int PineC = 0;     // Counter for Pineapples.
    int CocoC = 0;     // Counter for Coconuts.
    int PlanC = 0;     // Counter for Plantains.
    int BeetC = 0;     // Counter for Beets.
    int RadC = 0;      // Counter for Radishes.
    
    DecimalFormat decimalFormat = new DecimalFormat("#.##");

    public static void Outputter(int count, JLabel outP, JLabel outQ){
        final int TOTAL = 7; // final vairbale for bnumber of items
        int quantity [] = new int [TOTAL]; //make string array for quantity
        double total [] = new double [TOTAL]; //make string array for pricey
        try{
            FileReader file = new FileReader("Fruits.txt"); //get file for text
            
            BufferedReader buffer = new BufferedReader(file); //buffered reader (checks for spaces)
            for(int i = 0; i < TOTAL; i++){ //for loop
                quantity[i] = Integer.parseInt(buffer.readLine()); //puts first valeu into array for quanityt
                total[i] = Double.parseDouble(buffer.readLine()); //puts second value into array for price
            }
            buffer.close(); //ends the buffer
        }
        catch(IOException e){ //catch statement for exceptions
        }
        outQ.setText(String.valueOf(quantity[count-1])); //sets the label for quantity
        outP.setText(String.valueOf(total[count-1])); //sets the label for total
    }
    
    public Main() {
        initComponents();        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNMang = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LBLPMang = new javax.swing.JLabel();
        LBLQMang = new javax.swing.JLabel();
        BTNDrag = new javax.swing.JButton();
        LBLPDrag = new javax.swing.JLabel();
        LBLQDrag = new javax.swing.JLabel();
        BTNPine = new javax.swing.JButton();
        LBLPPine = new javax.swing.JLabel();
        LBLQPine = new javax.swing.JLabel();
        BTNCoco = new javax.swing.JButton();
        LBLPCoco = new javax.swing.JLabel();
        LBLQCoco = new javax.swing.JLabel();
        BTNPlan = new javax.swing.JButton();
        LBLPPlan = new javax.swing.JLabel();
        LBLQPlan = new javax.swing.JLabel();
        BTNBeet = new javax.swing.JButton();
        LBLPBeet = new javax.swing.JLabel();
        LBLQBeet = new javax.swing.JLabel();
        BTNRad = new javax.swing.JButton();
        LBLPRad = new javax.swing.JLabel();
        LBLQRad = new javax.swing.JLabel();
        BTNCBeet = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BTNCMang = new javax.swing.JButton();
        BTNCRad = new javax.swing.JButton();
        BTNCDrag = new javax.swing.JButton();
        BTNCCoco = new javax.swing.JButton();
        BTNCPlan = new javax.swing.JButton();
        BTNCPine = new javax.swing.JButton();
        LBLCRad = new javax.swing.JLabel();
        LBLCBeet = new javax.swing.JLabel();
        LBLCDrag = new javax.swing.JLabel();
        LBLCPine = new javax.swing.JLabel();
        LBLCCoco = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LBLCMang = new javax.swing.JLabel();
        LBLCPlan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LBLTotal = new javax.swing.JLabel();
        LBLGrand = new javax.swing.JLabel();
        BTNCheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Krish's Fruit Store");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Press the buttons below to find information about the items in our store");

        BTNMang.setText("Mangoes");
        BTNMang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMangActionPerformed(evt);
            }
        });

        jLabel3.setText("Price($)");

        jLabel4.setText("Quantity left");

        LBLPMang.setText("---");

        LBLQMang.setText("---");

        BTNDrag.setText("DragonFruit");
        BTNDrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDragActionPerformed(evt);
            }
        });

        LBLPDrag.setText("---");

        LBLQDrag.setText("---");

        BTNPine.setText("Pineapple");
        BTNPine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPineActionPerformed(evt);
            }
        });

        LBLPPine.setText("---");

        LBLQPine.setText("---");

        BTNCoco.setText("Coconuts");
        BTNCoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCocoActionPerformed(evt);
            }
        });

        LBLPCoco.setText("---");

        LBLQCoco.setText("---");

        BTNPlan.setText("Plantains");
        BTNPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPlanActionPerformed(evt);
            }
        });

        LBLPPlan.setText("---");

        LBLQPlan.setText("---");

        BTNBeet.setText("Beetroot");
        BTNBeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBeetActionPerformed(evt);
            }
        });

        LBLPBeet.setText("---");

        LBLQBeet.setText("---");

        BTNRad.setText("Radish");
        BTNRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRadActionPerformed(evt);
            }
        });

        LBLPRad.setText("---");

        LBLQRad.setText("---");

        BTNCBeet.setText("Beetroot");
        BTNCBeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCBeetActionPerformed(evt);
            }
        });

        jLabel5.setText("Add to Cart");

        BTNCMang.setText("Mangoes");
        BTNCMang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCMangActionPerformed(evt);
            }
        });

        BTNCRad.setText("Radish");
        BTNCRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCRadActionPerformed(evt);
            }
        });

        BTNCDrag.setText("DragonFruit");
        BTNCDrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCDragActionPerformed(evt);
            }
        });

        BTNCCoco.setText("Coconuts");
        BTNCCoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCCocoActionPerformed(evt);
            }
        });

        BTNCPlan.setText("Plantains");
        BTNCPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCPlanActionPerformed(evt);
            }
        });

        BTNCPine.setText("Pineapple");
        BTNCPine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCPineActionPerformed(evt);
            }
        });

        LBLCRad.setText("---");

        LBLCBeet.setText("---");

        LBLCDrag.setText("---");

        LBLCPine.setText("---");

        LBLCCoco.setText("---");

        jLabel6.setText("Cart");

        LBLCMang.setText("---");

        LBLCPlan.setText("---");

        jLabel7.setText("TOTAL:");

        jLabel8.setText("GRAND TOTAL:");

        jLabel9.setText("----------------");

        LBLTotal.setText("-");

        LBLGrand.setText("-");

        BTNCheck.setText("Check Out");
        BTNCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTNMang)
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(LBLPMang)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTNDrag)
                                        .addGap(18, 18, 18)
                                        .addComponent(LBLPDrag))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BTNPine)
                                            .addComponent(BTNCoco)
                                            .addComponent(BTNPlan)
                                            .addComponent(BTNBeet)
                                            .addComponent(BTNRad))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBLPRad)
                                            .addComponent(LBLPBeet)
                                            .addComponent(LBLPPlan)
                                            .addComponent(LBLPCoco)
                                            .addComponent(LBLPPine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(LBLQMang)
                                    .addComponent(LBLQDrag)
                                    .addComponent(LBLQPine)
                                    .addComponent(LBLQRad)
                                    .addComponent(LBLQBeet)
                                    .addComponent(LBLQPlan)
                                    .addComponent(LBLQCoco))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNCCoco)
                                    .addComponent(BTNCMang)
                                    .addComponent(jLabel5)
                                    .addComponent(BTNCDrag)
                                    .addComponent(BTNCPlan)
                                    .addComponent(BTNCPine)
                                    .addComponent(BTNCBeet)
                                    .addComponent(BTNCRad))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBLCRad)
                                    .addComponent(LBLCBeet)
                                    .addComponent(jLabel6)
                                    .addComponent(LBLCPlan)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(LBLCMang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LBLCDrag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(LBLCPine)
                                            .addComponent(LBLCCoco))
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BTNCheck)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(LBLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(LBLGrand, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BTNMang)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(LBLPMang)
                                                .addComponent(LBLQMang)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(BTNDrag)
                                            .addComponent(LBLPDrag)
                                            .addComponent(LBLQDrag)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(BTNCMang)
                                            .addComponent(LBLCMang))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(BTNCDrag)
                                            .addComponent(LBLCDrag))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BTNPine)
                                    .addComponent(LBLPPine)
                                    .addComponent(LBLQPine)
                                    .addComponent(BTNCPine)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(86, 86, 86)
                                .addComponent(LBLCPine)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNCoco)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LBLQCoco)
                                    .addComponent(BTNCCoco)
                                    .addComponent(LBLCCoco))
                                .addComponent(LBLPCoco))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNCheck)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(LBLTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(LBLGrand))
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel9)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNPlan)
                    .addComponent(LBLPPlan)
                    .addComponent(LBLQPlan)
                    .addComponent(BTNCPlan)
                    .addComponent(LBLCPlan))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNBeet)
                    .addComponent(LBLPBeet)
                    .addComponent(LBLQBeet)
                    .addComponent(BTNCBeet)
                    .addComponent(LBLCBeet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNRad)
                    .addComponent(LBLPRad)
                    .addComponent(LBLQRad)
                    .addComponent(BTNCRad)
                    .addComponent(LBLCRad))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNMangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMangActionPerformed
        // TODO add your handling code here:
        Outputter(1, LBLPMang, LBLQMang); //calls subroutine
    }//GEN-LAST:event_BTNMangActionPerformed

    private void BTNDragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDragActionPerformed
        // TODO add your handling code here:
        Outputter(2, LBLPDrag, LBLQDrag);//calls subroutine
    }//GEN-LAST:event_BTNDragActionPerformed

    private void BTNPineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPineActionPerformed
        // TODO add your handling code here:
        Outputter(3, LBLPPine, LBLQPine);//calls subroutine
    }//GEN-LAST:event_BTNPineActionPerformed

    private void BTNCocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCocoActionPerformed
        // TODO add your handling code here:
        Outputter(4, LBLPCoco, LBLQCoco);//calls subroutine
    }//GEN-LAST:event_BTNCocoActionPerformed

    private void BTNPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPlanActionPerformed
        // TODO add your handling code here:
        Outputter(5, LBLPPlan, LBLQPlan);//calls subroutine
    }//GEN-LAST:event_BTNPlanActionPerformed

    private void BTNBeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBeetActionPerformed
        // TODO add your handling code here:
        Outputter(6, LBLPBeet, LBLQBeet);//calls subroutine
    }//GEN-LAST:event_BTNBeetActionPerformed

    private void BTNRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRadActionPerformed
        // TODO add your handling code here:
        Outputter(7, LBLPRad, LBLQRad);//calls subroutine
    }//GEN-LAST:event_BTNRadActionPerformed

    private void BTNCBeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCBeetActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(LBLQBeet.getText()); //turns quantity into integer
        total--;//subtracts one from total
        BeetC += 1; //add one to cart
        LBLQBeet.setText(String.valueOf(total)); //set label to next number
        pricet = pricet + Double.parseDouble(LBLPBeet.getText()); //adds to price
        LBLCBeet.setText(String.valueOf(BeetC));//set label to next number
    }//GEN-LAST:event_BTNCBeetActionPerformed

    private void BTNCRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCRadActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(LBLQRad.getText());//turns quantity into integer
        total--;//subtracts one from total
        RadC += 1;//add one to cart
        LBLQRad.setText(String.valueOf(total));//set label to next number
        pricet = pricet + Double.parseDouble(LBLPRad.getText()); //adds to price
        LBLCRad.setText(String.valueOf(RadC));//set label to next number
    }//GEN-LAST:event_BTNCRadActionPerformed

    private void BTNCDragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCDragActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(LBLQDrag.getText());//turns quantity into integer
        total--;//subtracts one from total
        DragC += 1;//add one to cart
        LBLQDrag.setText(String.valueOf(total));//set label to next number
        pricet = pricet + Double.parseDouble(LBLPDrag.getText()); //adds to price
        LBLCDrag.setText(String.valueOf(DragC));//set label to next number
    }//GEN-LAST:event_BTNCDragActionPerformed

    private void BTNCCocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCCocoActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(LBLQCoco.getText());//turns quantity into integer
        total--;//subtracts one from total
        CocoC += 1;//add one to cart
        LBLQCoco.setText(String.valueOf(total));//set label to next number
        pricet = pricet + Double.parseDouble(LBLPCoco.getText()); //adds to price
        LBLCCoco.setText(String.valueOf(CocoC));//set label to next number
    }//GEN-LAST:event_BTNCCocoActionPerformed

    private void BTNCPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCPlanActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(LBLQPlan.getText());//turns quantity into integer
        total--;//subtracts one from total
        PlanC += 1;//add one to cart
        LBLQPlan.setText(String.valueOf(total));//set label to next number
        pricet = pricet + Double.parseDouble(LBLPPlan.getText()); //adds to price
        LBLCPlan.setText(String.valueOf(PlanC)); //set label to next number

    }//GEN-LAST:event_BTNCPlanActionPerformed

    private void BTNCMangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCMangActionPerformed
        // TODO add your handling code here:
       int total = Integer.parseInt(LBLQMang.getText());//turns quantity into integer
        total--; //subtracts one from total
        MangC += 1;//add one to cart
        LBLQMang.setText(String.valueOf(total));//set label to next number
        pricet = pricet + Double.parseDouble(LBLPMang.getText()); //adds to price
        LBLCMang.setText(String.valueOf(MangC)); //set label to next number
    }//GEN-LAST:event_BTNCMangActionPerformed

    private void BTNCPineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCPineActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(LBLQPine.getText());//turns quantity into integer
        total--;//subtracts one from total
        PineC += 1;//add one to cart
        LBLQPine.setText(String.valueOf(total));//set label to next number
        pricet = pricet + Double.parseDouble(LBLPPine.getText()); //adds to price
        LBLCPine.setText(String.valueOf(PineC)); //set label to next number
    }//GEN-LAST:event_BTNCPineActionPerformed

    private void BTNCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCheckActionPerformed
        // TODO add your handling code here:
        LBLTotal.setText(decimalFormat.format(pricet)); //calculates and displays total
        LBLGrand.setText(decimalFormat.format(pricet*1.13));//calculates and displays grand total
        
    }//GEN-LAST:event_BTNCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBeet;
    private javax.swing.JButton BTNCBeet;
    private javax.swing.JButton BTNCCoco;
    private javax.swing.JButton BTNCDrag;
    private javax.swing.JButton BTNCMang;
    private javax.swing.JButton BTNCPine;
    private javax.swing.JButton BTNCPlan;
    private javax.swing.JButton BTNCRad;
    private javax.swing.JButton BTNCheck;
    private javax.swing.JButton BTNCoco;
    private javax.swing.JButton BTNDrag;
    private javax.swing.JButton BTNMang;
    private javax.swing.JButton BTNPine;
    private javax.swing.JButton BTNPlan;
    private javax.swing.JButton BTNRad;
    private javax.swing.JLabel LBLCBeet;
    private javax.swing.JLabel LBLCCoco;
    private javax.swing.JLabel LBLCDrag;
    private javax.swing.JLabel LBLCMang;
    private javax.swing.JLabel LBLCPine;
    private javax.swing.JLabel LBLCPlan;
    private javax.swing.JLabel LBLCRad;
    private javax.swing.JLabel LBLGrand;
    private javax.swing.JLabel LBLPBeet;
    private javax.swing.JLabel LBLPCoco;
    private javax.swing.JLabel LBLPDrag;
    private javax.swing.JLabel LBLPMang;
    private javax.swing.JLabel LBLPPine;
    private javax.swing.JLabel LBLPPlan;
    private javax.swing.JLabel LBLPRad;
    private javax.swing.JLabel LBLQBeet;
    private javax.swing.JLabel LBLQCoco;
    private javax.swing.JLabel LBLQDrag;
    private javax.swing.JLabel LBLQMang;
    private javax.swing.JLabel LBLQPine;
    private javax.swing.JLabel LBLQPlan;
    private javax.swing.JLabel LBLQRad;
    private javax.swing.JLabel LBLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
