/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S300095291
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    public static boolean Checker(String value){
        try{
            int test = Integer.parseInt(value);
            return(true);
        }
        catch(NumberFormatException e){
            return(false);
        }
    }
    
    public static int Factorial(int fax){
        if(fax > 0){  
            return (fax*Factorial(fax-1));
        }
        else{
            return(1);
        }
    }
    
    public static String Primer(int pri, int check){
        boolean valid = false;
        double dpri = Double.parseDouble(String.valueOf(pri));
        double dcheck = Double.parseDouble(String.valueOf(check));
        while (dcheck > 1){
            valid = ((dpri/dcheck) % 1 == 0);
            dcheck = dcheck - 1;
            if (valid == true)
                return("No");
        }
        return("Yes");
    }
    
    public static int Fibonic(int term){
        int blah = 0;
        int blah1 = 0;
        int finale = 0;
        boolean valid = true;
        if (term == 1){
            return(1);
        }
        while(term > 0){
            finale = blah + blah1;
            if (valid == true)
                blah = finale;
            else
                blah1 = finale;
            if (blah == 0)
                blah = 1;
            valid = !valid;
            term--;
        }
        return(finale);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtFact = new javax.swing.JTextField();
        BtnFact = new javax.swing.JButton();
        TxtPrime = new javax.swing.JTextField();
        BtnPrime = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtFibo = new javax.swing.JTextField();
        BtnFibo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LblFact = new javax.swing.JLabel();
        LblPrime = new javax.swing.JLabel();
        LblFibo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Numbers");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Enter a number and click the button to find the factorial.");

        TxtFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFactActionPerformed(evt);
            }
        });

        BtnFact.setText("Factorial");
        BtnFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFactActionPerformed(evt);
            }
        });

        TxtPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrimeActionPerformed(evt);
            }
        });

        BtnPrime.setText("Prime");
        BtnPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrimeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Enter a number and click the button to determine whether it is a prime number or not.");

        TxtFibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFiboActionPerformed(evt);
            }
        });

        BtnFibo.setText("Fibonacci");
        BtnFibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFiboActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Enter a number and click the button to see the corresponding Fibonacci number.");

        LblFact.setText("---");

        LblPrime.setText("---");

        LblFibo.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtFact, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnFact)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblFact))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnPrime)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblPrime))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtFibo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnFibo)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblFibo)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFact)
                    .addComponent(LblFact))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPrime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPrime)
                    .addComponent(LblPrime))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFibo)
                    .addComponent(LblFibo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFactActionPerformed

    private void TxtPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrimeActionPerformed

    private void TxtFiboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFiboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFiboActionPerformed

    private void BtnFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFactActionPerformed
        // TODO add your handling code here:
        String factor = TxtFact.getText();
        int value;
        if (Checker(factor) == true){
            value = Integer.parseInt(factor);
            LblFact.setText(String.valueOf(Factorial(value)));
        }
        else{
            LblFact.setText("The value entered is not a number. Try again.");
        }
        
    }//GEN-LAST:event_BtnFactActionPerformed

    private void BtnPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeActionPerformed
        // TODO add your handling code here:
        String prime = TxtPrime.getText();
        int value;
        if (Checker(prime) == true){
            value = Integer.parseInt(prime);
            LblPrime.setText(String.valueOf(Primer(value, value-1)));
        }
        else{
            LblPrime.setText("The value entered is not a number. Try again.");
        }
        
    }//GEN-LAST:event_BtnPrimeActionPerformed

    private void BtnFiboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiboActionPerformed
        // TODO add your handling code here:
        String fibo = TxtFibo.getText();
        int value;
        if (Checker(fibo) == true){
            value = Integer.parseInt(fibo);
            LblFibo.setText(String.valueOf(Fibonic(value)));
        }
        else{
            LblFibo.setText("The value entered is not a number. Try again.");
        }
    }//GEN-LAST:event_BtnFiboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFact;
    private javax.swing.JButton BtnFibo;
    private javax.swing.JButton BtnPrime;
    private javax.swing.JLabel LblFact;
    private javax.swing.JLabel LblFibo;
    private javax.swing.JLabel LblPrime;
    private javax.swing.JTextField TxtFact;
    private javax.swing.JTextField TxtFibo;
    private javax.swing.JTextField TxtPrime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
