/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nalam
 */
public class FrmDiceGame extends javax.swing.JFrame {

    int totalRolls = 0; //initializes and sets total rolls
    int totalCorrect = 0;//initializes and sets correct rolls
    int totalIncorrect = 0;//initializes and sets incorrect rolls
    int userGuess;//initializes users Guess number
    int computerGuess;//initializes computers Guess number
    int diceRoll; //initializes dice roll number
    int userBet; //initializes users bet amount
    int computerBet; // initializes computers bet amount
    int userMoney = 200; //initializes and sets users money
    int computerMoney = 200; //initializes and sets computers money
    double percCorrect = 0; //initializes percent correct

    
    /**
     * Creates new form FrmDiceGame
     */
    public FrmDiceGame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255)); //sets background colour

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblWelcomePrompt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserGuess = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUserBet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblComputerGuess = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblComputerBet = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblUserMoney = new javax.swing.JLabel();
        lblComputerMoney = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblRollsValue = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();
        btnRollDice = new javax.swing.JButton();
        lblRollValue = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblOutputMsg = new javax.swing.JLabel();
        ProgressMoney = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitle.setText("Krish's Dice Guessing Game");

        lblWelcomePrompt.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblWelcomePrompt.setText("Enter a number from 1-6, place your bet, and click roll to roll the dice");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("YOUR GUESS (1-6):");

        txtUserGuess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserGuess.setText("0");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("YOUR BET AMOUNT ($):");

        txtUserBet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserBet.setText("0");
        txtUserBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserBetActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("COMPUTERS GUESS (1-6):");

        lblComputerGuess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComputerGuess.setText("0");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("COMPUTERS BET AMOUNT ($):");

        lblComputerBet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComputerBet.setText("$0");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("YOUR MONEY:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("COMPUTER MONEY:");

        lblUserMoney.setText("$200");

        lblComputerMoney.setText("$200");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Number of Rolls:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Number of Correct Guesses:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Number of Incorrect Guesses:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Percent of Correct Guesses:");

        lblIncorrectValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIncorrectValue.setText("0");

        lblRollsValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRollsValue.setText("0");

        lblCorrectValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorrectValue.setText("0");

        lblPercentValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPercentValue.setText("0%");

        btnRollDice.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRollDice.setText("ROLL DICE");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        lblRollValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRollValue.setText("0");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        jLabel14.setText("Rules:");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setText("1. Place bets that are lower or equal to the amount of money you have ");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setText("2. If you win a round, you will recieve the money the computer bets");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel25.setText("3. To win the game the computer must have $0.00; You would have $400.00 ");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel26.setText("4. If you have $0.00 you lose; Computer would have $400.00");

        lblOutputMsg.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        lblOutputMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutputMsg.setText("Start Playing The Game!");

        ProgressMoney.setMaximum(400);
        ProgressMoney.setValue(200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Project (1).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Project (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWelcomePrompt)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblComputerBet, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUserGuess)
                                        .addComponent(txtUserBet)
                                        .addComponent(lblComputerGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUserMoney))
                            .addComponent(lblComputerMoney, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRollDice, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(lblRollValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProgressMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPercentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRollsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(lblIncorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))))
                        .addContainerGap(19, Short.MAX_VALUE))))
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOutputMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle)
                    .addComponent(ProgressMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcomePrompt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lblUserMoney))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblComputerGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblComputerBet, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblComputerMoney))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRollDice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRollValue, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(lblRollsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblCorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(lblIncorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(lblPercentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblOutputMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
    
        diceRoll = (int)Math.round(Math.random()*5+1); //randomly rolls dice number
        lblRollValue.setText(String.valueOf(diceRoll)); //sets label as dice number
        
        computerGuess = (int)Math.round(Math.random()*5+1); //randomly rolls computers guess number
        lblComputerGuess.setText(String.valueOf(computerGuess));//randomly sets computers bet amount
        computerBet = (int)Math.round(Math.random()*(computerMoney-1)+1);//sets label as computers guess number
        lblComputerBet.setText("$" + String.valueOf(computerBet));//sets label as computers bet amount
        
        userGuess = Integer.parseInt(txtUserGuess.getText()); //gets user guess number
        userBet = Integer.parseInt(txtUserBet.getText()); //gets users bet amount
        
        totalRolls += 1; //adds 1 to the amount of rolls
        
        if (userGuess == computerGuess) 
        {
            lblOutputMsg.setText("You and Computer were both right...");
            if (diceRoll == userGuess)
            {
                totalCorrect += 1;
            }
            else
            {
                totalIncorrect -= 1;
            }
            //adjusts counters in case user Guess and Computer guess is same
        }
        //if statement for checking if both computer and user was right (does nothing)
        
        else if (diceRoll == userGuess) //if user was correct...
        {
            totalCorrect += 1; //add 1 to amount of correct guesses
            userMoney += computerBet; //get the amount of money computer bet
            lblUserMoney.setText("$" + String.valueOf(userMoney)); //sets the new amount of money user has
            computerMoney -= computerBet; //takes away money from computer
            lblComputerMoney.setText("$" + String.valueOf(computerMoney)); //sets new amount of money computer has
            if (userMoney == 400)
            {
                lblOutputMsg.setText("YOU WIN!!!!!  :)");
            }
            // if statement if user gets all the money and wins
            else if (userMoney > 300)
            {
                lblOutputMsg.setText("Almost There!! A few more guesses to win!!");
            }
            else if (userMoney >= 100)
            {
                lblOutputMsg.setText("Great Job!! Keep Playing to Win!!");
            }
            else if (userMoney < 100)
            {
                lblOutputMsg.setText("Phew! Good Job on winning that one.");
            }
            //all if statements to send custom msgs when the user wins based on amount of money user now has
        }
        else if (diceRoll == computerGuess)//if computer was correct...
        {
            totalIncorrect += 1;//add 1 to amount of correct guesses
            computerMoney += userBet;
            lblComputerMoney.setText("$" + String.valueOf(computerMoney));
            userMoney -= userBet;
            lblUserMoney.setText("$" + String.valueOf(userMoney));
            if (computerMoney == 400)
            {
                lblOutputMsg.setText("Awww... You Lose :(");
            }
            else if (computerMoney > 300)
            {
                lblOutputMsg.setText("Oh No, The Computer is very close to Winning...");
            }
            else if (computerMoney >= 1)
            {
                lblOutputMsg.setText("Computer won this time but it hasn't won the game yet...");
            }

        }
        else
        {
            lblOutputMsg.setText("Oh No, No one got it right! Try again!!");
            totalIncorrect += 1;
        }
        
        
        percCorrect = ((double)totalCorrect/(double)totalRolls)*100;
        
        percCorrect = percCorrect * 100;
        percCorrect = Math.round(percCorrect);
        percCorrect = percCorrect / 100;
        
        lblRollsValue.setText(String.valueOf(totalRolls));
        lblCorrectValue.setText(String.valueOf(totalCorrect));
        lblIncorrectValue.setText(String.valueOf(totalIncorrect));
        lblPercentValue.setText(String.valueOf(percCorrect) + "%");
        ProgressMoney.setValue(userMoney);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRollDiceActionPerformed

    private void txtUserBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserBetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserBetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDiceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressMoney;
    private javax.swing.JButton btnRollDice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblComputerBet;
    private javax.swing.JLabel lblComputerGuess;
    private javax.swing.JLabel lblComputerMoney;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblOutputMsg;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblRollValue;
    private javax.swing.JLabel lblRollsValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserMoney;
    private javax.swing.JLabel lblWelcomePrompt;
    private javax.swing.JTextField txtUserBet;
    private javax.swing.JTextField txtUserGuess;
    // End of variables declaration//GEN-END:variables
}
