/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S300095291
 */
public class MAIN extends javax.swing.JFrame {

    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 192, 205));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtCube = new javax.swing.JTextField();
        BTNCube = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtFirst = new javax.swing.JTextField();
        BTNPow = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxtDeg = new javax.swing.JTextField();
        BTNDeg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TxtValue = new javax.swing.JTextField();
        BTNValue = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TxtSideA = new javax.swing.JTextField();
        BTNHypo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TxtSqaure = new javax.swing.JTextField();
        BTNSquare = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TxtRad = new javax.swing.JTextField();
        BTNRad = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TxtLog = new javax.swing.JTextField();
        BTNLog = new javax.swing.JButton();
        TxtSecond = new javax.swing.JTextField();
        TxtSideB = new javax.swing.JTextField();
        LblPow = new javax.swing.JLabel();
        LblDeg = new javax.swing.JLabel();
        LblCube = new javax.swing.JLabel();
        LblValue = new javax.swing.JLabel();
        LblHypo = new javax.swing.JLabel();
        LblSquare = new javax.swing.JLabel();
        LblLog = new javax.swing.JLabel();
        LblRad = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setText("Krish Magic Math Methods");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Enter an integer. The program will display the CUBE ROOT of the integer. ");

        TxtCube.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCube.setText("0");
        TxtCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCubeActionPerformed(evt);
            }
        });

        BTNCube.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNCube.setText("CUBE ROOT");
        BTNCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCubeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Enter two numbers. The program will display the first number to the power of the second number.");

        TxtFirst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtFirst.setText("0");
        TxtFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFirstActionPerformed(evt);
            }
        });

        BTNPow.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNPow.setText("POWER");
        BTNPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPowActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Enter an angle in radians. The program will display the angle in DEGREES. ");

        TxtDeg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtDeg.setText("0");
        TxtDeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDegActionPerformed(evt);
            }
        });

        BTNDeg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNDeg.setText("DEGREES");
        BTNDeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDegActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Enter an number. The program will display the ABSOLUTE VALUE of the number. ");

        TxtValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtValue.setText("0");
        TxtValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValueActionPerformed(evt);
            }
        });

        BTNValue.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNValue.setText("ABSOLUTE VALUE");
        BTNValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNValueActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Enter the length of two sides of a right angle triangle. The program will display the HYPOTENUSE of the triangle. ");

        TxtSideA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSideA.setText("0");
        TxtSideA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSideAActionPerformed(evt);
            }
        });

        BTNHypo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNHypo.setText("HYPOTENUSE");
        BTNHypo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHypoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Enter a positive integer. The program will display the SQUARE ROOT of the integer. ");

        TxtSqaure.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSqaure.setText("0");
        TxtSqaure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSqaureActionPerformed(evt);
            }
        });

        BTNSquare.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNSquare.setText("SQUARE ROOTS");
        BTNSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSquareActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Enter an angle in degrees. The program will display the angle in RADIANS. ");

        TxtRad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtRad.setText("0");
        TxtRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRadActionPerformed(evt);
            }
        });

        BTNRad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNRad.setText("RADIANS");
        BTNRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRadActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Enter a positive number. The program will display the NATURAL LOGARITHM of the NUMBER. ");

        TxtLog.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtLog.setText("0");
        TxtLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLogActionPerformed(evt);
            }
        });

        BTNLog.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BTNLog.setText("NATURAL LOG");
        BTNLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLogActionPerformed(evt);
            }
        });

        TxtSecond.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSecond.setText("0");
        TxtSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSecondActionPerformed(evt);
            }
        });

        TxtSideB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSideB.setText("0");
        TxtSideB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSideBActionPerformed(evt);
            }
        });

        LblPow.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblPow.setText("ANSWER");

        LblDeg.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblDeg.setText("ANSWER");

        LblCube.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblCube.setText("ANSWER");

        LblValue.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblValue.setText("ANSWER");

        LblHypo.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblHypo.setText("ANSWER");

        LblSquare.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblSquare.setText("ANSWER");

        LblLog.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblLog.setText("ANSWER");

        LblRad.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        LblRad.setText("ANSWER");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\S300095291\\Downloads\\9184756.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtDeg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNDeg)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblDeg))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNValue)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblValue))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtSqaure, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNSquare)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblSquare))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtRad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNRad)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblRad))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtLog, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNLog)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblLog))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TxtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TxtSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNPow)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblPow))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TxtSideA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TxtSideB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNHypo)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblHypo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtCube, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNCube)
                                                .addGap(18, 18, 18)
                                                .addComponent(LblCube)))))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNCube)
                            .addComponent(LblCube)))
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTNPow, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblPow)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDeg)
                    .addComponent(LblDeg))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNValue)
                    .addComponent(LblValue))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtSideA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtSideB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTNHypo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblHypo)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSqaure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSquare)
                    .addComponent(LblSquare))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtRad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNRad)
                    .addComponent(LblRad))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNLog)
                    .addComponent(LblLog))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCubeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCubeActionPerformed

    private void BTNCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCubeActionPerformed
        // TODO add your handling code here:
        
        double cube = Double.parseDouble(TxtCube.getText()); //initializes variable and gets text inputted by user to later use for math method calculation;
        LblCube.setText(String.valueOf(Math.cbrt(cube))); //sets label to string value of math method of variable
        
    }//GEN-LAST:event_BTNCubeActionPerformed

    private void TxtFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFirstActionPerformed

    private void BTNPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPowActionPerformed
        // TODO add your handling code here:
        
        double powone = Double.parseDouble(TxtFirst.getText()); //initializes variable and gets text inputted by user to later use for math method calculation);
        double powtwo = Double.parseDouble(TxtSecond.getText()); //initializes variable and gets text inputted by user to later use for math method calculation));
        LblPow.setText(String.valueOf(Math.pow(powone, powtwo))); //sets label to string value of math method of variable
        
    }//GEN-LAST:event_BTNPowActionPerformed

    private void TxtDegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDegActionPerformed

    private void BTNDegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDegActionPerformed
        // TODO add your handling code here:
        
        double deg = Double.parseDouble(TxtDeg.getText()); //initializes variable and gets text inputted by user to later use for math method calculation
        LblDeg.setText(String.valueOf(Math.toRadians(deg))); //sets label to string value of math method of variable
        
    }//GEN-LAST:event_BTNDegActionPerformed

    private void TxtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValueActionPerformed

    private void BTNValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNValueActionPerformed
        // TODO add your handling code here:
        
        double abso = Double.parseDouble(TxtValue.getText()); //initializes variable and gets text inputted by user to later use for math method calculation);
        LblValue.setText(String.valueOf(Math.abs(abso))); //sets label to string value of math method of variable
        
    }//GEN-LAST:event_BTNValueActionPerformed

    private void TxtSideAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSideAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSideAActionPerformed

    private void BTNHypoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHypoActionPerformed
        // TODO add your handling code here:
        
        double hypone = Double.parseDouble(TxtSideA.getText()); //initializes variable and gets text inputted by user to later use for math method calculation);
        double hyptwo = Double.parseDouble(TxtSideB.getText()); //initializes variable and gets text inputted by user to later use for math method calculation);
        
        LblHypo.setText(String.valueOf(Math.hypot(hypone, hyptwo))); //sets label to string value of math method of variable
        
    }//GEN-LAST:event_BTNHypoActionPerformed

    private void TxtSqaureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSqaureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSqaureActionPerformed

    private void BTNSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSquareActionPerformed
        // TODO add your handling code here:

        double root = Double.parseDouble(TxtSqaure.getText()); //initializes variable and gets text inputted by user to later use for math method calculation));
        LblSquare.setText(String.valueOf(Math.sqrt(root))); //sets label to string value of math method of variable
        
    }//GEN-LAST:event_BTNSquareActionPerformed

    private void TxtRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRadActionPerformed

    private void BTNRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRadActionPerformed
        // TODO add your handling code here:
        
        double rad = Double.parseDouble(TxtRad.getText()); //initializes variable and gets text inputted by user to later use for math method calculation
        LblRad.setText(String.valueOf(Math.toDegrees(rad))); //sets label to string value of math method of variable
        
    }//GEN-LAST:event_BTNRadActionPerformed

    private void TxtLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLogActionPerformed

    private void BTNLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLogActionPerformed
        // TODO add your handling code here:
        
        double log = Double.parseDouble(TxtLog.getText()); //initializes variable and gets text inputted by user to later use for math method calculation
        LblLog.setText(String.valueOf(Math.log(log))); //sets label to string value of math method of variable
        
    }//GEN-LAST:event_BTNLogActionPerformed

    private void TxtSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSecondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSecondActionPerformed

    private void TxtSideBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSideBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSideBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCube;
    private javax.swing.JButton BTNDeg;
    private javax.swing.JButton BTNHypo;
    private javax.swing.JButton BTNLog;
    private javax.swing.JButton BTNPow;
    private javax.swing.JButton BTNRad;
    private javax.swing.JButton BTNSquare;
    private javax.swing.JButton BTNValue;
    private javax.swing.JLabel LblCube;
    private javax.swing.JLabel LblDeg;
    private javax.swing.JLabel LblHypo;
    private javax.swing.JLabel LblLog;
    private javax.swing.JLabel LblPow;
    private javax.swing.JLabel LblRad;
    private javax.swing.JLabel LblSquare;
    private javax.swing.JLabel LblValue;
    private javax.swing.JTextField TxtCube;
    private javax.swing.JTextField TxtDeg;
    private javax.swing.JTextField TxtFirst;
    private javax.swing.JTextField TxtLog;
    private javax.swing.JTextField TxtRad;
    private javax.swing.JTextField TxtSecond;
    private javax.swing.JTextField TxtSideA;
    private javax.swing.JTextField TxtSideB;
    private javax.swing.JTextField TxtSqaure;
    private javax.swing.JTextField TxtValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
